# Generated by Django 3.1.12 on 2025-04-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20250404_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='win',
            new_name='medails',
        ),
        migrations.CreateModel(
            name='PlayerTimePerSeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100)),
                ('seed', models.CharField(max_length=100)),
                ('time_played', models.FloatField()),
                ('date_played', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('player_id', 'seed')},
            },
        ),
    ]
