# Generated by Django 3.1.12 on 2025-04-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20250408_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='seedStockage',
            fields=[
                ('seed', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
